apiVersion: v1
kind: Service
metadata:
  name: {{ template "ldap_proxy.fullname" . }}
  labels:
    release: {{ template "ldap_proxy.fullname" . }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: {{ .Values.service.protocol }}
      name: {{ .Values.service.name }}
  selector:
    app: {{ template "ldap_proxy.name" . }}
    release: {{ .Release.Name }}
  status:
    loadBalancer: {}
